global:
  scrape_interval: 5s #scrape every 5 seconds
  evaluation_interval: 5s #evaluate rules every 5 secs

rule_files:
#  - "one_rule.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['127.0.9.1:9090']
  - job_name: 'spring-boot-app'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['host.docker.internal:8080'] #host and port

    basic_auth:
      username: "admin"
      password: "pass"
